# Generated by Django 4.2.27 on 2025-12-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0010_channelsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "checkin_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StructureCheckInTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_templates",
                        to="structures.structure",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="structure_links",
                        to="checkin.checkintemplate",
                    ),
                ),
            ],
            options={
                "db_table": "structure_checkin_templates",
                "ordering": ["-is_active", "assigned_at"],
                "unique_together": {("structure", "template")},
            },
        ),
        migrations.CreateModel(
            name="CheckInTemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique per template (used as key in payload)",
                        max_length=255,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("help_text", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text area"),
                            ("select", "Select"),
                            ("radio", "Radio"),
                            ("checkbox", "Checkbox"),
                            ("date", "Date"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("file", "File"),
                            ("number", "Number"),
                        ],
                        default="text",
                        max_length=32,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("main", "Main guest"),
                            ("additional", "Additional guest"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=16,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_required", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="checkin.checkintemplate",
                    ),
                ),
            ],
            options={
                "db_table": "checkin_template_fields",
                "ordering": ["order", "id"],
                "unique_together": {("template", "slug")},
            },
        ),
    ]
