# Generated by Django 4.2.27 on 2025-12-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkintemplatefield",
            unique_together=set(),
        ),
    ]
