# Generated by Django 5.2 on 2025-05-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "__first__"),
        ("properties", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("length_of_stay", models.IntegerField()),
                ("adults_count", models.IntegerField()),
                ("children_count", models.IntegerField(default=0)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("city_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("payment_details", models.JSONField(blank=True, null=True)),
                ("invoice_info", models.JSONField(blank=True, null=True)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("citations", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="guests.guest",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
            },
        ),
    ]
