# Generated by Django 4.2.25 on 2025-10-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0010_channelsettings"),
        ("properties", "0005_remove_propertytype_image_urls_and_more"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="payment_details",
        ),
        migrations.AddField(
            model_name="booking",
            name="cleaning_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="other_extra_fees",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash on Arrival"),
                    ("credit_card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("online", "Online Payment"),
                ],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partially_paid", "Partially Paid"),
                    ("fully_paid", " Fully Paid"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="structure",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="structures.structure",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="city_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
