# Generated by Django 4.2.25 on 2025-10-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0002_remove_booking_payment_details_booking_cleaning_fee_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="guest",
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partially_paid", "Partially Paid"),
                    ("fully_paid", "Fully Paid"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
