# Generated by Django 4.2.25 on 2025-10-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_remove_propertytype_image_urls_and_more"),
        ("bookings", "0003_remove_booking_guest_alter_booking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="property_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="properties.propertytype",
            ),
        ),
    ]
