# Generated by Django 4.2.25 on 2025-10-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="due_at_property",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount still due to be paid at the property (applicable for direct bookings)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("booking_com", "Booking.com"),
                    ("airbnb", "Airbnb"),
                    ("expedia", "Expedia"),
                    ("direct", "Direct"),
                    ("other", "Other"),
                ],
                default="direct",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="platform_reservation_id",
            field=models.CharField(
                blank=True,
                help_text="Reservation ID from external platform (e.g., Airbnb, Booking.com)",
                max_length=255,
                null=True,
            ),
        ),
    ]
