# Generated by Django 4.2.25 on 2025-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_due_at_property_booking_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="platform",
            field=models.TextField(
                blank=True,
                choices=[
                    ("booking_com", "Booking.com"),
                    ("airbnb", "Airbnb"),
                    ("expedia", "Expedia"),
                    ("direct", "Direct"),
                    ("other", "Other"),
                ],
                default="direct",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="platform_reservation_id",
            field=models.CharField(
                blank=True, help_text="Comma-separated amenities list", null=True
            ),
        ),
    ]
