# Generated by Django 4.2.25 on 2025-10-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_booking_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="platform",
            field=models.TextField(
                blank=True, help_text="Comma-separated platforms list", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="platform_reservation_id",
            field=models.CharField(
                blank=True,
                help_text="Reservation ID from external platform (e.g., Airbnb, Booking.com)",
                max_length=255,
                null=True,
            ),
        ),
    ]
