# Generated by Django 4.2.25 on 2025-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_booking_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="due_at_property",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Amount still due to be paid at the property (applicable for direct bookings)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
