# Generated by Django 4.2.27 on 2025-12-15 08:35

from django.db import migrations, models
import uuid


def backfill_booking_uid(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for booking in Booking.objects.filter(uid__isnull=True):
        booking.uid = uuid.uuid4()
        booking.save(update_fields=["uid"])

class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_booking_due_at_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="uid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Public UID for guest check-in access",
                unique=False,
            ),
        ),
        migrations.RunPython(backfill_booking_uid),
    ]
