# Generated by Django 4.2.27 on 2025-12-20 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_alter_booking_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="uid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Public UID for guest check-in access",
                unique=True,
            ),
        ),
    ]
