# Generated by Django 4.2.27 on 2025-12-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_add_uid_unique"),
        ("bookings", "0011_alter_booking_uid"),
    ]

    operations = []
