# Generated by Django 4.2.25 on 2025-11-17 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0010_channelsettings"),
        ("properties", "0005_remove_propertytype_image_urls_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("availability", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_blocked_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_periods",
                        to="properties.property",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_periods",
                        to="properties.propertytype",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_periods",
                        to="structures.structure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_blocked_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blocked_periods",
                "ordering": ["-start_date"],
            },
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
        migrations.AddIndex(
            model_name="blockedperiod",
            index=models.Index(
                fields=["property", "start_date", "end_date"],
                name="blocked_per_propert_58df69_idx",
            ),
        ),
    ]
