# Generated by Django 4.2.25 on 2025-10-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="passport_number",
            new_name="id_number",
        ),
        migrations.RenameField(
            model_name="guest",
            old_name="country",
            new_name="nationality",
        ),
        migrations.RenameField(
            model_name="guest",
            old_name="special_requests",
            new_name="notes",
        ),
    ]
