# Generated by Django 4.2.25 on 2025-10-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_remove_booking_guest_alter_booking_payment_status"),
        ("guests", "0002_rename_passport_number_guest_id_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="guest",
            old_name="notes",
            new_name="guest_notes",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="position",
        ),
        migrations.AddField(
            model_name="guest",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
