# Generated by Django 4.2.25 on 2025-10-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0003_alter_guest_options_rename_notes_guest_guest_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="country_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="document_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="document_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="document_issuing_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("id_card", "ID Card"),
                    ("drivers_license", "Driver's License"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
