# Generated by Django 4.2.25 on 2025-10-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0004_guest_country_of_birth_guest_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="postal_code",
            new_name="zip_code",
        ),
        migrations.AddField(
            model_name="guest",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
