# Generated by Django 4.2.25 on 2025-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0005_rename_postal_code_guest_zip_code_guest_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
