# Generated by Django 4.2.27 on 2025-12-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0006_guest_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Store template-driven additional/custom fields for this guest (keyed by field slug).",
                null=True,
            ),
        ),
    ]
