# Generated by Django 5.2 on 2025-07-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, help_text="Property Type Name"),
                ),
                (
                    "internal_property_type_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        help_text="Optional internal property ID",
                    ),
                ),
                (
                    "property_size_sqm",
                    models.DecimalField(
                        blank=True,
                        null=True,
                        max_digits=8,
                        decimal_places=2,
                        help_text="Size in square meters",
                    ),
                ),
                ("max_guests", models.IntegerField(default=0)),
                ("num_beds", models.IntegerField(default=0)),
                ("num_sofa_beds", models.IntegerField(default=0)),
                ("num_bedrooms", models.IntegerField(default=0)),
                ("num_bathrooms", models.IntegerField(default=0)),
                (
                    "amenities",
                    models.TextField(
                        blank=True,
                        null=True,
                        help_text="Comma-separated amenities list",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_types",
                        to="structures.structure",
                        db_index=True,
                    ),
                ),
            ],
            options={
                "db_table": "property_types",
                "indexes": [
                    models.Index(
                        fields=["structure"], name="propertytype_structure_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, help_text="Property Name")),
                (
                    "internal_property_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        help_text="Optional Property ID",
                    ),
                ),
                (
                    "floor_number",
                    models.IntegerField(
                        blank=True, null=True, help_text="Floor Number"
                    ),
                ),
                (
                    "amenities",
                    models.TextField(
                        blank=True,
                        null=True,
                        help_text="Comma-separated amenities list",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="structures.structure",
                        db_index=True,
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="properties.propertytype",
                        db_index=True,
                    ),
                ),
            ],
            options={
                "db_table": "properties",
                "indexes": [
                    models.Index(
                        fields=["structure"], name="propertytype_structure_idx_v2"
                    ),
                ],
            },
        ),
    ]
