# Generated by Django 5.2.3 on 2025-07-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyTypeBed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_type", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="property",
            name="propertytype_structure_idx_v2",
        ),
        migrations.RemoveIndex(
            model_name="propertytype",
            name="propertytype_structure_idx",
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Unavailable"), (2, "Available")],
                default=1,
                help_text="Use Status Enum: 1=Unavailable, 2=Available, etc.",
            ),
        ),
        migrations.AddField(
            model_name="propertytype",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Unmapped"), (2, "Mapped")],
                default=1,
                help_text="Use Status Enum: 1=Unmapped, 2=Mapped, etc.",
            ),
        ),
        migrations.AddField(
            model_name="propertytypebed",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="properties.propertytype",
            ),
        ),
    ]
