# Generated by Django 5.2.3 on 2025-07-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_propertytypebed_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="propertytypebed",
            table="property_types_beds",
        ),
    ]
