# Generated by Django 5.2.5 on 2025-08-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_propertytypebed_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertytype",
            name="image_urls",
            field=models.JSONField(
                default=list, help_text="List of Cloudinary image URLs"
            ),
        ),
    ]
