# Generated by Django 5.2.5 on 2025-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_propertytype_image_urls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertytype",
            name="image_urls",
        ),
        migrations.AddField(
            model_name="propertytype",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
