# Generated by Django 5.2 on 2025-07-01 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, help_text="Structure Name")),
                (
                    "structure_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        help_text="Internal property ID / type",
                    ),
                ),
                (
                    "internal_reference_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        help_text="Internal Reference Code",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(max_length=100)),
                (
                    "legal_entity_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tax_id_vat_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "default_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "default_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("time_zone", models.CharField(blank=True, max_length=50, null=True)),
                ("default_check_in_time", models.TimeField(blank=True, null=True)),
                ("default_check_out_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                    ),
                ),
            ],
            options={
                "db_table": "structures",
            },
        ),
    ]
