# Generated by Django 5.2.5 on 2025-08-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
