# Generated by Django 5.2.5 on 2025-08-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0002_structure_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=8,
            ),
        ),
    ]
