# Generated by Django 5.2.5 on 2025-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0003_structure_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="base_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="occupancy",
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="rating",
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="total_units",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="structure_type",
            field=models.CharField(
                help_text="Internal property ID / type", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="zip_code",
            field=models.CharField(max_length=20),
        ),
    ]
