# Generated by Django 5.2.5 on 2025-08-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0004_structure_base_price_structure_occupancy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="occupancy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="rating",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("active", "Active"), ("inactive", "Inactive")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="total_units",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
