# Generated by Django 5.2.5 on 2025-08-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "structures",
            "0005_alter_structure_occupancy_alter_structure_rating_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="occupancy",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=8,
                null=True,
            ),
        ),
    ]
