# Generated by Django 5.2.4 on 2025-09-19 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0006_alter_structure_occupancy_alter_structure_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="user",
            field=models.ForeignKey(
                help_text="Owner of the structure",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_structures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StructureUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Editor", "Editor"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        help_text="User's role in this structure",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who added this user to the structure",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_structure_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_users",
                        to="structures.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_structures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "structure_users",
                "ordering": ["-created_at"],
                "unique_together": {("structure", "user")},
            },
        ),
        migrations.AddField(
            model_name="structure",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have access to this structure",
                related_name="accessible_structures",
                through="structures.StructureUser",
                through_fields=("structure", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
