# Generated by Django 5.2.4 on 2025-09-19 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0008_structureinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the invitee", max_length=254
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Editor", "Editor"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        help_text="Role to assign in structure",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Personal message from inviter", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User created from this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        help_text="Structure to invite user to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="structures.structure",
                    ),
                ),
            ],
            options={
                "db_table": "invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="StructureInvitation",
        ),
    ]
