# Generated by Django 5.2.4 on 2025-09-19 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0009_invitation_delete_structureinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_booking_type",
                    models.CharField(
                        choices=[("relative", "Relative"), ("absolute", "Absolute")],
                        default="relative",
                        help_text="Default booking type: Relative or Absolute",
                        max_length=10,
                    ),
                ),
                (
                    "default_booking_value",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Default booking value (days for relative, specific value for absolute)",
                    ),
                ),
                (
                    "default_booking_until_date",
                    models.DateField(
                        blank=True,
                        help_text="Default booking until date (for absolute type)",
                        null=True,
                    ),
                ),
                (
                    "individual_accommodations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Property-specific booking settings override",
                    ),
                ),
                (
                    "booking_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% increase from base price for Booking.com (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "airbnb_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% increase from base price for Airbnb (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "expedia_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% increase from base price for Expedia (0-100)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_channel_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.OneToOneField(
                        help_text="Structure these settings belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_settings",
                        to="structures.structure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_channel_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Setting",
                "verbose_name_plural": "Channel Settings",
                "db_table": "channel_settings",
            },
        ),
    ]
