# Generated by Django 5.2.3 on 2025-07-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0003_alter_propertytypebed_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default/base price for the night",
                        max_digits=10,
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum nights required"
                    ),
                ),
                (
                    "booking",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price on Booking.com",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "airbnb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price on Airbnb",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "experia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price on Expedia",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_rates",
                "ordering": ["property_id", "date"],
                "unique_together": {("property", "date")},
            },
        ),
    ]
