# Generated by Django 4.2.25 on 2025-10-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0002_remove_booking_payment_details_booking_cleaning_fee_and_more",
        ),
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="booking_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the booking occupying this rate slot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rates",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
