# Generated by Django 5.2.4 on 2025-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="super_admin",
            field=models.BooleanField(
                default=True, help_text="Super admin has full database access"
            ),
        ),
    ]
