# Generated by Django 5.2.4 on 2025-09-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_super_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(
                blank=True, help_text="Company name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_logo_url",
            field=models.URLField(
                blank=True, help_text="Company logo URL", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Profile image URL", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(
                blank=True, help_text="Job title/position", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="User's phone number", max_length=20, null=True
            ),
        ),
    ]
