# Generated by Django 5.2.4 on 2025-09-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_two_factor_enabled_loginsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="property_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of properties managed by user"
            ),
        ),
    ]
